[profile.default]
solc_version = "0.7.6"
src = "src"
out = "out"
libs = ["lib"]
exclude = ["lib/**"]
dotenv = true
gas_price = 1000000000
optimizer = true
optimizer_runs = 200

fs_permissions = [
    { access = "read", path = "./whitelist.json" }
]

remappings = [
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
